# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Pull StepFunctionLocal and publish as Node.js Package

on:
  push:
    paths:
      - .github/workflows/npm-publish.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Download and verify StepFunctions Local
        # https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-jar.html
        run: |
          curl -s -L https://s3.amazonaws.com/stepfunctionslocal/StepFunctionsLocal.tar.gz | tee StepFunctionsLocal.tar.gz | md5sum -c <(echo "$(curl -s -L https://s3.amazonaws.com/stepfunctionslocal/StepFunctionsLocal.tar.gz.md5)  -")

      - name: Extract and run
        run: |
            tar -xz StepFunctionsLocal.tar.gz
            java -jar StepFunctionsLocal.jar -v
            ls -la

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
