# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Pull StepFunctionLocal and publish as Node.js Package

on:
  schedule:
    # run on every day on 6:01
    - cron: "1 6 * * *"
  push:
    paths:
      - .github/workflows/npm-publish.yml

jobs:
  download-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Download and verify StepFunctions Local
        # https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-jar.html
        run: |
          curl -s -L https://s3.amazonaws.com/stepfunctionslocal/StepFunctionsLocal.tar.gz | tee StepFunctionsLocal.tar.gz | md5sum -c <(echo "$(curl -s -L https://s3.amazonaws.com/stepfunctionslocal/StepFunctionsLocal.tar.gz.md5)  -")

      - name: Extract and run
        run: |
            tar zxvf StepFunctionsLocal.tar.gz
            java -jar StepFunctionsLocal.jar -v

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Set the version
        id: get-version
        run: |
          version=$(java -jar StepFunctionsLocal.jar -v | grep -m 1 -Po '(?<=Version: )\d+.\d+.\d+')
          echo "StepFunctions Local version $version"
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version $version --force
          echo "new-version=$version" >> "$GITHUB_OUTPUT"

      - run: |
          npm config set max_body_size 1000mb
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Get changelog line
        id: get-changelog
        run: |
          changelog=$(grep -Po "Version: ${{ steps.get-version.outputs.new-version }} - \K.+" README.txt)
          echo $changelog
          echo "changelog=$changelog" >> "$GITHUB_OUTPUT"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: StepFunctionsLocal.tar.gz
          makeLatest: true
          body: ${{ steps.get-changelog.outputs.changelog }}
          tag: v${{ steps.get-version.outputs.new-version }}
          allowUpdates: true
